# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/protocolbuffers/protobuf-go
%global goipath         google.golang.org/protobuf
%global forgeurl        https://github.com/protocolbuffers/protobuf-go
Version:                1.31.0

%gometa
%global import_path     %{goipath}

%global common_description %{expand:
Go support for Google's protocol buffers.}

%global godocs          CONTRIBUTING.md README.md

Name:           golang-google-protobuf
Release:        1%{?dist}
Summary:        Go support for Google's protocol buffers

%global godevelheader   %{expand:
Obsoletes:              compat-golang-github-protobuf-devel < 1.31.0-3
}

License:        BSD-3-Clause
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  protobuf-compiler
Requires:       protobuf

Provides:       protoc-gen-go = %{version}-%{release}
Provides:       golang(%{goipath}/protoc-gen-go) = %{version}-%{release}

%description
%{common_description}

%package -n %{goname}-devel
Summary:	%{summary}
BuildArch:  noarch
%description -n %{goname}-devel
%{common_description}

%prep
%setup -q

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
install -d -p %{buildroot}/%{gopath}/src/%{import_path}/
for file in $(find . -iname "*.go" \! -iname "*_test.go" \! -iname "main.go" ) ; do
    echo "%%dir %%{gopath}/src/%%{import_path}/$(dirname $file)" >> devel.file-list
    install -d -p %{buildroot}/%{gopath}/src/%{import_path}/$(dirname $file)
    cp -pav $file %{buildroot}/%{gopath}/src/%{import_path}/$file
    echo "%%{gopath}/src/%%{import_path}/$file" >> devel.file-list
done

# source codes for building projects
install -d -p %{buildroot}/%{gopath}/src/%{import_path}/
echo "%%dir %%{gopath}/src/%%{import_path}/." >> devel.file-list
# find all *.s and generate devel.file-list
for file in $(find . -iname "*.s") ; do
    echo "%%dir %%{gopath}/src/%%{import_path}/$(dirname $file)" >> devel.file-list
    install -d -p %{buildroot}/%{gopath}/src/%{import_path}/$(dirname $file)
    cp -pav $file %{buildroot}/%{gopath}/src/%{import_path}/$file
    echo "%%{gopath}/src/%%{import_path}/$file" >> devel.file-list
done
# find all *.c and generate devel.file-list
for file in $(find . -iname "*.c") ; do
    echo "%%dir %%{gopath}/src/%%{import_path}/$(dirname $file)" >> devel.file-list
    install -d -p %{buildroot}/%{gopath}/src/%{import_path}/$(dirname $file)
    cp -pav $file %{buildroot}/%{gopath}/src/%{import_path}/$file
    echo "%%{gopath}/src/%%{import_path}/$file" >> devel.file-list
done
# find all *.go but no *_test.go files and generate devel.file-list
for file in $(find . -iname "*.go" \! -iname "*_test.go") ; do
    echo "%%dir %%{gopath}/src/%%{import_path}/$(dirname $file)" >> devel.file-list
    install -d -p %{buildroot}/%{gopath}/src/%{import_path}/$(dirname $file)
    cp -pav $file %{buildroot}/%{gopath}/src/%{import_path}/$file
    echo "%%{gopath}/src/%%{import_path}/$file" >> devel.file-list
done
cat devel.file_list
sort -u -o devel.file-list devel.file-list
install -m 0755 -vd %{buildroot}%{gopath}/src/%(dirname %{oldgoipath})
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{rhel} != 8
%if %{with check}
%check
%gocheck
%endif
%endif

%files
%files -n %{goname}-devel -f devel.file-list

%changelog
